[package]
name = "vox3"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "26.0.1"
winit = "0.29.15"
log = "0.4.28"
env_logger = "0.11.8"
cgmath = "0.18.0"
futures = "0.3.31"
bytemuck = "1.24.0"
rand = "0.9.2"
